### ISSUE TITLE
Configure custom domain

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#1]
## Description

- Serve the site from the domain `williamwu.site`.
- GitHub docs: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

## Tasks

- [x] Verify the domain on GitHub
- [x] Add the custom domain in the repo settings
- [x] Ensure "Enforce HTTPS" is enabled
- [x] Create an `A` record with the DNS provider
- [x] Confirm the DNS record is configured correctly with `dig`
- [x] _Consider:_ Redirect from `www` subdomain to the bare domain

**Comment by wllmwu** [comment]
Complete!
