### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#10]
## Description

- **As a** site visitor,
- **I want** to see the pages that are available,
- **So that** I can easily find my way around and come back to different pages.

Tentative site structure:

- Home (`/`)
- About (`/about`)
  - Link to resume (`/resume`)
- Apps (`/apps`)
  - Math Keeper (`/apps/math-keeper`)
  - Copy Better (`/apps/copy-better`)
  - Snake, Cubed (`/apps/snake-cubed`)
  - HarvestHaul (`/apps/harvesthaul`)
- Projects (`/projects`)
  - TSE projects...?
  - Course grapher (name? consider hosting?)
- Resources (`/resources`)
  - LaTeX
    - Quick reference
    - Guide (part 1...?)
  - Git
    - Quick reference
    - Guide?
  - Minecraft stuff...
- Contact (`/contact`)
- Privacy policy(ies) for apps (`/privacy`; not in nav bar---link in footer)

## Requirements

- Scenario 1: Top level, no subpages
  - Given I am at the home page (`/`),
  - When I click on "About" in the navigation bar,
  - Then I am sent to the about page (`/about`).
- Scenario 2: Top level, with subpages
  - Given I am at the home page (`/`),
  - When I click on "Apps" in the navigation bar,
  - Then I am sent to the apps page (`/apps`).
- Scenario 3: Subpage
  - Given I am at the home page (`/`),
  - When I hover over "Apps" in the navigation bar,
  - And then click on "Copy Better" in the dropdown menu,
  - Then I am sent to the Copy Better page (`/apps/copy-better`).
- Scenario 4: No index, with subpages
  - Given I am at the home page (`/`),
  - When I hover over "Resources" in the navigation bar,
  - And then click on "LaTeX" in the dropdown menu,
  - Then I stay at the home page.

## Tasks

- [x] Lay out placeholders for the tentative site structure
- [x] Create navigation bar component with top-level page links
- [x] Style navigation bar
- [x] Add navigation bar to `_app.js` (see https://nextjs.org/docs/basic-features/layouts)
- [x] Add second-level submenus
- [x] Add third-level submenus (possibly generalize to allow for arbitrary page nesting, although deeper than three levels probably won't be needed)
- [POSTPONED] _Consider:_ Add support for "directories" with no index pages (see Scenario 4) - do this later if it becomes desired
- [x] Check generated static output

**Comment by wllmwu** [comment]
Submenus are now generalized for arbitrarily nested pages
