### ISSUE TITLE
Page footer

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#11]
## Description

- **As a** site visitor,
- **I want** to have access to important links at the bottom of each page,
- **So that** I can quickly find them when I am done reading.

The page footer should contain the following items:

- Copyright information
- Site design tidbits? (fonts, framework/stack, ...)
- Contact information and/or link to contact page
- Privacy policy(ies) for apps

## Requirements

- Pretty straightforward

## Tasks

- [x] Create footer component
- [x] Add footer to `Layout`
- [x] Check generated static output
