### ISSUE TITLE
MDX processing

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#12]
## Description

- Set up the official Next.js MDX integration (see https://nextjs.org/docs/advanced-features/using-mdx).

## Tasks

- [x] Install and configure `@next/mdx`
- [x] Add placeholder `pages/index.mdx` (home page)
- [x] Set styles for elements
  - Headings
  - Paragraphs
  - Block quotes
  - Unordered lists
  - Ordered lists
  - Emphasis (italic) and strong (bold)
  - Inline code and code blocks
  - Links

Postponing the following tasks until the need arises:
- _Consider:_ Use a plugin or package for syntax highlighting
- _Consider:_ Use a plugin for GitHub-Flavored Markdown (see https://github.com/remarkjs/remark-gfm)
- _Consider:_ Use a plugin for generating links to headings (see https://github.com/rehypejs/rehype-slug, https://github.com/rehypejs/rehype-autolink-headings)
