### ISSUE TITLE
Resource pages

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#140]
## Description

Add and organize resource pages under `/resources`.

## Tasks

- [ ] Add LaTeX guide
- [ ] Add web dev frontend guide
- [ ] Organize Python resources
