### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#17]
## Description

- Home page (path: `/`) with a banner, short introduction, and quick links
  - ~~Likely a one-off page format so it can be written in React instead of Markdown~~

## Tasks

- [x] Create and style banner/splash image component
- [x] Add title metadata to page `<head>` tags
- [POSTPONED] Create the actual splash image (maybe a simple one for now to be replaced in the future)
- [x] Write introduction copy
- [x] Create and style quick/featured link components
- [ ] Add site favicon
