### ISSUE TITLE
Migrate to Vite

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#201]
## Description

- Create React App is deprecated and Next.js is unnecessary for this use case (plus kind of annoying to maintain)
- Rebuild the project using Vite and copy over React components

## Tasks

- [x] Build new project using Vite
- [x] Copy over components
- [x] Copy over pages
- [x] Remove old project
- [x] Update deploy action
