### ISSUE TITLE
App pages

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#21]
## Description

- Apps page (path: `/apps`) with links to all subpages and also app store links
- Page for each app with description, update notes, app store link
  - `/apps/math-keeper`
  - `/apps/copy-better`
  - `/apps/snake-cubed`
  - `/apps/harvesthaul`

## Tasks

- [ ] Create apps page
- [ ] Create Math Keeper page
- [ ] Create Copy Better page
- [ ] Create Snake, Cubed page
- [ ] Create HarvestHaul page
