### ISSUE TITLE
Privacy pages

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#23]
## Description

- Privacy page (path: `/privacy`) with links to individual privacy policy subpages
- Page for each privacy policy
  - `/privacy/math-keeper`
  - `/privacy/copy-better`
  - `/privacy/snake-cubed`

## Tasks

- [x] Create privacy page
- [x] Create Math Keeper privacy policy page
- [x] Create Copy Better privacy policy page
- [x] Create Snake, Cubed privacy policy page
