### ISSUE TITLE
Frontmatter support

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#25]
## Description

- Add support for frontmatter in MDX files

## Tasks

- [x] Research remark/rehype and relevant plugins
- [x] Install `remark-frontmatter` plugin and add to Next config
- [x] Refactor the inner page parts of the `Layout` component into a separate `Page` component which can receive frontmatter metadata
- [x] Write a custom plugin which takes the resulting AST from `remark-frontmatter`, parses the frontmatter node, and compiles the frontmatter into an export with `Page` wrapping the contents
  - May be similar to [`remark-mdx-frontmatter`](https://github.com/remcohaszing/remark-mdx-frontmatter)
  - Also see the "Layouts" section in https://nextjs.org/docs/advanced-features/using-mdx
- [x] Check generated output
