### ISSUE TITLE
Set up Next.js project

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#5]
## Description

See tasks

## Tasks

- [x] Replace repo contents with a new Next.js TypeScript project
- [x] Configure project for hosting on GitHub Pages
- [x] Create a `gh-pages` branch and set as the publishing source

**Comment by wllmwu** [comment]
First deployment successful! See b56b3a3c33f28bc0536f110a4cd322e81af5ebb2
