### ISSUE TITLE
Navigation within pages

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#55]
## Description

- **As a** site visitor,
- **I want** to jump to different sections of a guide or other long page,
- **So that** I can quickly access the parts that I need to refer to.

This feature is in preparation for writing guides, e.g. for Git and LaTeX.

## Tasks

- [x] Investigate possible approaches to automatic table of contents generation
  - A remark plugin called `remark-toc` exists, but it doesn't do quite what we want. However, it wraps around `mdast-util-toc`, which may be useful
- [x] Add heading wrapper components that include `id` attributes on heading elements (using the slugified heading text) and associated `<a>` tags
  - Refer to https://nextjs.org/docs/advanced-features/using-mdx#custom-elements for MDX provider information
- [x] Write a remark or rehype plugin that traverses the content of a Markdown page and adds a table of contents at the beginning of the page OR do this in a React component (traverse the DOM in a `useEffect` hook or use a context which the heading wrappers hook into)
  - Try using [`mdast-util-toc`](https://github.com/syntax-tree/mdast-util-toc)
  - Consider also inserting `<section>` tags
- [x] Use the plugin when `showTOC: true` is in a page's frontmatter
- [x] Add CSS for heading self-links and table of contents
- [x] Add back-to-top link
