### ISSUE TITLE
Miscellaneous minor changes

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#59]
## Description

- See tasks

## Tasks

- [x] Update resume for August 2022
- [x] Add accessibility as an interest
- ~~_Consider:_ Change body text to a narrower serif typeface~~
- [x] Automatically merge Dependabot pull requests for semver patch versions in addition to minor versions
