### ISSUE TITLE
Add GitHub Actions workflow for CI/CD

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#6]
## Description

- Add an Actions workflow which does the following:
  - (Checkout, set up Node, etc.)
  - Build and export the Next app
  - Push the `out` directory to the `gh-pages` branch
- The workflow is triggered by new pushes to `main` and can also be manually triggered
- Ideally, the workflow runs without modifying/committing to remote `main`

## Tasks

- [ ] Add the new workflow
- [ ] Remove `out` directory from `main` and revert `.gitignore`
- [ ] Test the new workflow
