### ISSUE TITLE
Content updates December 2022

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/wllmwu.github.io#86]
## Description

- See tasks

## Tasks

- [x] Add page for course grapher project
- [x] Add updated resume
- [x] Add new favicon
